# Generated by Django 4.2.1 on 2023-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerdata",
            name="amount_spent",
        ),
        migrations.RemoveField(
            model_name="customerdata",
            name="category",
        ),
        migrations.RemoveField(
            model_name="customerdata",
            name="date",
        ),
        migrations.RemoveField(
            model_name="customerdata",
            name="mode_of_payments",
        ),
        migrations.AddField(
            model_name="customerdata",
            name="EMI_paid_on_time",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
