# Generated by Django 4.2.1 on 2023-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_remove_customerdata_amount_spent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_Id", models.IntegerField()),
                ("category", models.CharField(max_length=20)),
                ("mode_of_payments", models.CharField(max_length=25)),
                ("amount_spent", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
    ]
